function showpath(paths, S0, m)
% ------------------------------------------------------
% display first m paths generated by forward Euler
% eg: paths = pathBS1d(S0, r, sig, T, M, K)
% ------------------------------------------------------
% paths = paths generated by numerical SDE   (M-by-K matrix)
% S0    = initial value                      (float)
% m     = number of displayped paths         (int)
% ------------------------------------------------------
for i = 1:m
    plot( 0:size(paths,2) , [S0,paths(i,:)], '.-'); hold on;
end
title([num2str(m), ' paths of asset price']);
xlabel('time'); ylabel('price');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% showpath(paths, S0, 50)